### ISSUE TITLE
released vs retained

### ISSUE THREAD

**Issue by JuliaCoates** [pfmc-assessments/copper_rockfish_2023#7]
https://github.com/pfmc-assessments/copper_rockfish_2023/blob/ded5955582503ec37299f528e3138bea610293c0/docs/data_workshop/5_fishery_composition_data.Rmd#L70

Should the sentence read "All lengths below represent retained fish" and not released?

**Comment by chantelwetzel-noaa** [comment]
Good catch. Correct with commit ca5aae223f538991d2c91a3ccb800e0ec4a4e20b
